export const RESPONSE = [
  {
    vehicle_name: "vehicle 1",
    vehicle_status: {
      elevation: "200m",
      temprature: "45",
      locked: true,
      battery: "75.6",
      throttle: true,
      controller: true,
      motor: true,
      overLoad: true,
      overCurrent: true,
    },
    vehicle_statistics: {},
    vehicle_trip_detail: [
      {
        strt_time: "1653542305",
        duration: "25 min",
        mx_speed: "91 kmph",
        avg_speed: "54 kmph",
        strt_voltage: "70.04v",
        end_voltage: "69.4v",
        distance: "5.4 km",
        driver_score: "98.5",
      },
    ],
  },
  {
    vehicle_name: "vehicle 2",
    vehicle_status: {
      elevation: "250m",
      temprature: "48",
      locked: true,
      battery: "78.6",
      throttle: false,
      controller: true,
      motor: false,
      overLoad: true,
      overCurrent: true,
    },
    vehicle_statistics: {},
    vehicle_trip_detail: [
      {
        strt_time: "1653542306",
        duration: "28 min",
        mx_speed: "71 kmph",
        avg_speed: "58 kmph",
        strt_voltage: "65.04v",
        end_voltage: "50.4v",
        distance: "5.8 km",
        driver_score: "97.5",
      },
    ],
  },
  {
    vehicle_name: "vehicle 3",
    vehicle_status: {
      elevation: "300m",
      temprature: "50",
      locked: true,
      battery: "78.6",
      throttle: true,
      controller: true,
      motor: true,
      overLoad: true,
      overCurrent: true,
    },
    vehicle_statistics: {},
    vehicle_trip_detail: [
      {
        strt_time: "1653542307",
        duration: "28 min",
        mx_speed: "95 kmph",
        avg_speed: "57 kmph",
        strt_voltage: "78.04v",
        end_voltage: "68.4v",
        distance: "7 km",
        driver_score: "94.5",
      },
    ],
  },
  {
    vehicle_name: "vehicle 4",
    vehicle_status: {
      elevation: "350m",
      temprature: "40",
      locked: true,
      battery: "65.6",
      throttle: true,
      controller: true,
      motor: true,
      overLoad: true,
      overCurrent: true,
    },
    vehicle_statistics: {},
    vehicle_trip_detail: [
      {
        strt_time: "1653542308",
        duration: "22 min",
        mx_speed: "99 kmph",
        avg_speed: "50 kmph",
        strt_voltage: "60.04v",
        end_voltage: "50.4v",
        distance: "9 km",
        driver_score: "91.5",
      },
    ],
  },
];
